### PR TITLE
iot-dash

### PR DESCRIPTION
**Pull request by iovidius**
Hi! 

Great work on the library. I added an implementation (iot-dash) to the examples folder.

I also changed some minor things:
- Fixed "OnDisconnect" typo
- Changed it to newest .NET Framework
- Changed PostBuildEvent because the old one was throwing errors

I like to hear what you think.

Jos

### CODE REVIEW

**Comment by iovidius** [comment]
Hmm, this is because of the PostBuildEvent commands ...

**Review by fvanroie — APPROVED** [review]

**Review by fvanroie — APPROVED** [review]

**Review by fvanroie — CHANGES_REQUESTED** [review]
I'm not keen of adding pre-compiled binaries to the examples folder, please remove this dll.

**Review by fvanroie — CHANGES_REQUESTED** [review]
Download link should point to the releases page of the repo fvanroie /
MqttClientPlugin

**Review by fvanroie — APPROVED** [review]

**Review by fvanroie — APPROVED** [review]

**Review by fvanroie — APPROVED** [review]

**Comment by fvanroie** [comment]
Thank you for your contribution!

**Pull request merged**
