### PR TITLE
Add openWB-pv-visualization example

### PR DESCRIPTION
**Pull request by yankee42**
Here another example :-). It is the first time ever I did anything with Rainmeter, so... it is likely that this could be improved. Everyone should feel free to use and improve it.

### CODE REVIEW

**Comment by yankee42** [comment]
Maybe the example is not the best in current state and you should not use it after all. It looks like the Histogram actually displays relative values and so if maxConsumption <> maxProduction the proportions get all wrong.

I am attempting to fix this by using
```
[powerConsumptionRelativeToProduction]
Measure=Calc
Formula=powerConsumption
MinValue=0
MaxValue=#maxProduction#
```
Und use that for the histogram, but... I'll see tomorrow whether it works. Also it is not really pretty for an example, because that will then only work if maxProduction > maxConsumption...

**Comment by fvanroie** [comment]
Thanks, I'll have a closer look over the weekend. It's always good to have examples to build upon. The histogram images looks very neat! Keep us posted on your findings if the measurements do work correct 👍

**Comment by yankee42** [comment]
Just as a short update in the meantime... I have the impression that this displays correctly most of the time. However something is wrong. Maybe I totally misunderstand the "histogram". I am trying to [get some help in the Rainmeter forum](https://forum.rainmeter.net/viewtopic.php?f=5&t=36524).

**Comment by fvanroie** [comment]
Not sure because I haven't used histogram either, but maybe you need to direct Rainmeter to use the [percentual value](https://docs.rainmeter.net/manual/variables/section-variables/#Percentual) instead: 
```
[graph]
Meter=Histogram
AutoScale=1
MeasureName=[powerProduction:%]
MeasureName2=[powerConsumption:%]
```

**Comment by fvanroie** [comment]
I will this example as-is. We can update it if a better way to calculate the histogram values comes up.

**Comment by yankee42** [comment]
OK... Actually it works correctly most of the time after all. To bad I did a solution for the "morning-anomality"... Maybe someone will eventually figure something out.

**Pull request merged**
